using System.Diagnostics;
using System.Diagnostics.Metrics;
using SerialMemory.Core.Interfaces;
using SerialMemory.Core.Telemetry;

namespace SerialMemory.Worker.Classification;

/// <summary>
/// Background worker that detects and processes historical memories missing L1-L4 layers.
/// Runs on startup and periodically to ensure 100% of memories have all classification layers.
/// Implements rate limiting to avoid overloading DB and LLMs.
/// </summary>
public sealed class HistoricalMemoryProcessor : BackgroundService
{
    private readonly IMemoryBackfillService _backfillService;
    private readonly ILogger<HistoricalMemoryProcessor> _logger;
    private readonly string _workerId;

    // Configuration
    private readonly TimeSpan _initialDelay = TimeSpan.FromSeconds(30); // Wait for other services to start
    private readonly TimeSpan _pollingInterval = TimeSpan.FromMinutes(2); // Check every 2 minutes
    private readonly TimeSpan _idleInterval = TimeSpan.FromMinutes(5); // When no work, check less frequently
    private readonly int _batchSize = 25;

    // Metrics
    private static readonly Counter<long> _memoriesProcessed = Metrics.Meter.CreateCounter<long>(
        "historical_processor_memories_processed",
        description: "Total memories processed by historical processor");

    private static readonly Counter<long> _layersGenerated = Metrics.Meter.CreateCounter<long>(
        "historical_processor_layers_generated",
        description: "Total layers generated by historical processor");

    private static readonly Counter<long> _processingErrors = Metrics.Meter.CreateCounter<long>(
        "historical_processor_errors",
        description: "Total errors in historical processor");

    private static readonly Histogram<double> _batchDuration = Metrics.Meter.CreateHistogram<double>(
        "historical_processor_batch_duration_seconds",
        description: "Duration of batch processing in seconds");

    private static readonly ObservableGauge<int> _pendingMemories = Metrics.Meter.CreateObservableGauge(
        "historical_processor_pending_memories",
        () => _lastKnownPendingCount,
        description: "Number of memories pending processing");

    private static int _lastKnownPendingCount;

    public HistoricalMemoryProcessor(
        IMemoryBackfillService backfillService,
        ILogger<HistoricalMemoryProcessor> logger)
    {
        _backfillService = backfillService;
        _logger = logger;
        _workerId = $"historical-processor-{Environment.MachineName}-{Guid.CreateVersion7():N}";
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation(
            "Historical Memory Processor {WorkerId} starting (initialDelay={InitialDelay}, pollingInterval={PollingInterval}, batchSize={BatchSize})",
            _workerId, _initialDelay, _pollingInterval, _batchSize);

        // Initial delay to let other services start
        await Task.Delay(_initialDelay, stoppingToken);

        // Log initial statistics
        await LogBackfillStatisticsAsync(stoppingToken);

        var consecutiveEmptyBatches = 0;

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                var stats = await _backfillService.GetBackfillStatisticsAsync(stoppingToken);
                _lastKnownPendingCount = stats.UnprocessedMemories + stats.PartiallyProcessedMemories;

                if (_lastKnownPendingCount == 0)
                {
                    consecutiveEmptyBatches++;

                    if (consecutiveEmptyBatches == 1)
                    {
                        _logger.LogInformation(
                            "All memories are fully processed ({Total} total, {Complete}% complete). Entering idle mode.",
                            stats.TotalMemories, stats.CompletionPercentage);
                    }

                    // Use longer interval when idle
                    await Task.Delay(_idleInterval, stoppingToken);
                    continue;
                }

                consecutiveEmptyBatches = 0;

                _logger.LogInformation(
                    "Found {Pending} memories needing processing (total={Total}, complete={Complete}%, failed={Failed})",
                    _lastKnownPendingCount, stats.TotalMemories, stats.CompletionPercentage, stats.FailedMemories);

                // Process a batch
                var result = await ProcessBatchAsync(stoppingToken);

                if (result.TotalMemoriesProcessed > 0)
                {
                    _memoriesProcessed.Add(result.TotalMemoriesProcessed);
                    _layersGenerated.Add(result.TotalLayersGenerated);

                    _logger.LogInformation(
                        "Batch complete: processed={Processed}, succeeded={Succeeded}, partial={Partial}, failed={Failed}, layers={Layers}",
                        result.TotalMemoriesProcessed,
                        result.SuccessfullyCompleted,
                        result.PartiallyCompleted,
                        result.Failed,
                        result.TotalLayersGenerated);
                }

                // Adaptive polling: shorter interval if there's more work
                var interval = _lastKnownPendingCount > 100
                    ? TimeSpan.FromMinutes(1)
                    : _pollingInterval;

                await Task.Delay(interval, stoppingToken);
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                break;
            }
            catch (Exception ex)
            {
                _processingErrors.Add(1);
                _logger.LogError(ex, "Error in historical memory processor loop");

                // Exponential backoff on errors
                await Task.Delay(TimeSpan.FromSeconds(30), stoppingToken);
            }
        }

        _logger.LogInformation("Historical Memory Processor {WorkerId} stopping", _workerId);
    }

    private async Task<BackfillResult> ProcessBatchAsync(CancellationToken ct)
    {
        var sw = Stopwatch.StartNew();

        try
        {
            // Get unprocessed memories
            var unprocessed = await _backfillService.GetUnprocessedMemoriesAsync(
                limit: _batchSize,
                tenantId: null, // Process all tenants
                ct: ct);

            if (unprocessed.Count == 0)
            {
                return new BackfillResult
                {
                    TotalMemoriesProcessed = 0,
                    StartedAt = DateTimeOffset.UtcNow,
                    CompletedAt = DateTimeOffset.UtcNow
                };
            }

            _logger.LogDebug(
                "Processing batch of {Count} memories (oldest: {OldestDate})",
                unprocessed.Count,
                unprocessed.Min(m => m.CreatedAt));

            var processed = 0;
            var succeeded = 0;
            var partial = 0;
            var failed = 0;
            var totalLayers = 0;
            var errors = new List<string>();

            foreach (var memory in unprocessed)
            {
                if (ct.IsCancellationRequested)
                    break;

                try
                {
                    _logger.LogDebug(
                        "Processing memory {MemoryId} (tenant={TenantId}, missing=[{MissingLayers}], retries={RetryCount})",
                        memory.MemoryId,
                        memory.TenantId,
                        string.Join(", ", memory.MissingLayers),
                        memory.RetryCount);

                    var result = await _backfillService.ProcessMemoryWithIdempotencyAsync(
                        memory.TenantId,
                        memory.MemoryId,
                        maxRetries: 3,
                        ct: ct);

                    processed++;
                    totalLayers += result.LayersGenerated.Length;

                    if (result.IsFullyProcessed)
                    {
                        succeeded++;
                        _logger.LogDebug(
                            "Memory {MemoryId} fully processed (generated={Generated}, skipped={Skipped})",
                            memory.MemoryId,
                            result.LayersGenerated.Length,
                            result.LayersSkipped.Length);
                    }
                    else if (result.LayersGenerated.Length > 0)
                    {
                        partial++;
                        _logger.LogDebug(
                            "Memory {MemoryId} partially processed (generated={Generated}, failed=[{Failed}])",
                            memory.MemoryId,
                            result.LayersGenerated.Length,
                            string.Join(", ", result.LayersFailed));
                    }
                    else if (result.LayersFailed.Length > 0)
                    {
                        failed++;
                        _processingErrors.Add(1);
                        foreach (var error in result.Errors)
                        {
                            errors.Add($"Memory {memory.MemoryId} {error.Key}: {error.Value}");
                        }
                    }

                    // Rate limiting: small delay between memories to avoid LLM overload
                    await Task.Delay(100, ct);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Unexpected error processing memory {MemoryId}", memory.MemoryId);
                    failed++;
                    _processingErrors.Add(1);
                    errors.Add($"Memory {memory.MemoryId}: {ex.Message}");
                }
            }

            sw.Stop();
            _batchDuration.Record(sw.Elapsed.TotalSeconds);

            return new BackfillResult
            {
                TotalMemoriesProcessed = processed,
                SuccessfullyCompleted = succeeded,
                PartiallyCompleted = partial,
                Failed = failed,
                TotalLayersGenerated = totalLayers,
                Duration = sw.Elapsed,
                Errors = errors,
                StartedAt = DateTimeOffset.UtcNow - sw.Elapsed,
                CompletedAt = DateTimeOffset.UtcNow
            };
        }
        catch (Exception ex)
        {
            sw.Stop();
            _logger.LogError(ex, "Failed to process batch");

            return new BackfillResult
            {
                TotalMemoriesProcessed = 0,
                Failed = 1,
                Errors = [ex.Message],
                Duration = sw.Elapsed,
                StartedAt = DateTimeOffset.UtcNow - sw.Elapsed,
                CompletedAt = DateTimeOffset.UtcNow
            };
        }
    }

    private async Task LogBackfillStatisticsAsync(CancellationToken ct)
    {
        try
        {
            var stats = await _backfillService.GetBackfillStatisticsAsync(ct);
            _lastKnownPendingCount = stats.UnprocessedMemories + stats.PartiallyProcessedMemories;

            _logger.LogInformation(
                """
                Historical Memory Processor Statistics:
                  Total Memories: {Total}
                  Fully Processed: {FullyProcessed} ({CompletionPct}%)
                  Partially Processed: {Partial}
                  Unprocessed: {Unprocessed}
                  Failed: {Failed}
                  Queued: {Queued}
                """,
                stats.TotalMemories,
                stats.FullyProcessedMemories,
                stats.CompletionPercentage,
                stats.PartiallyProcessedMemories,
                stats.UnprocessedMemories,
                stats.FailedMemories,
                stats.QueuedMemories);

            if (stats.ByLayer.Count > 0)
            {
                _logger.LogInformation("Layer counts: {ByLayer}",
                    string.Join(", ", stats.ByLayer.Select(kv => $"{kv.Key}={kv.Value}")));
            }

            if (stats.ByTenant.Count > 0)
            {
                _logger.LogInformation("Unprocessed by tenant: {ByTenant}",
                    string.Join(", ", stats.ByTenant.Select(kv => $"{kv.Key}={kv.Value}")));
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to get backfill statistics");
        }
    }
}
