FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["SerialMemory.Web/SerialMemory.Web.csproj", "SerialMemory.Web/"]
COPY ["SerialMemory.Core/SerialMemory.Core.csproj", "SerialMemory.Core/"]
RUN dotnet restore "SerialMemory.Web/SerialMemory.Web.csproj"
COPY . .
WORKDIR "/src/SerialMemory.Web"
RUN dotnet build "SerialMemory.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SerialMemory.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SerialMemory.Web.dll"]
